### ISSUE TITLE
FB meta

### ISSUE THREAD

**Issue by halfempty** [everythingtype/calcott#43]
@ncalcott Have you shared pages from the site on FB? If yes, has the result been good-- ie. it's capturing meta tags and images properly? If no, we can add some cues in there for it

**Comment by ncalcott** [comment]
Sorry about the silence!  Turns out github was associated with an old e-mail address and I wasn't receiving any of these messages...

**Comment by ncalcott** [comment]
At any rate, I haven't really shared anything on Facebook, but I can certainly test it out.  Frankly, it's not a super priority for me, but I do believe it was working...
