### ISSUE TITLE
Thumbnail size options

### ISSUE THREAD

**Issue by halfempty** [everythingtype/calcott#46]
> Inside Portfolios there are three size options, three column, two column, and 1 column.

I've added a field for this to the back-end. 

@ncalcott Hold off for a sec on using this, as I want to do a bit more testing to make sure this fieldset will work for this use. I'll update this soon!

**Comment by halfempty** [comment]
@gehalber @KyleETC Okay, multiple sizes! Is this how you envisioned it?

http://www.nicholascalcott.com/portfolios/still-lifes-for-metropolis/

**Comment by gehalber** [comment]
Hot!

**Comment by halfempty** [comment]
@gehalber @KyleETC @ncalcott

Great! Please feel free to use the new fields to set sizes. If you encounter anything unexpected, please let me know

**Comment by ncalcott** [comment]
Quick question on this - the 2 column size always seems to float right.  I don't necessarily need control over which side, but I'd prefer it to not always be the same side...

**Comment by halfempty** [comment]
@ncalcott The algorithm attempts to put things as high-up as possible. It's not preferring one side over the other, really. That's probably just a coincidence / how things are shaking out.

**Comment by ncalcott** [comment]
OK, I'll keep an eye on it.

**Comment by ncalcott** [comment]
Yep, you're right, it's functioning normally.  You can close this issue, if you want.  Thanks!

**Comment by ncalcott** [comment]
Question - is the max size still set to 1024, or whatever it was?  I'd like to have the three column ones be the full width of the site, but I don't necessarily want to change the max size in the slideshows...

**Comment by gehalber** [comment]
I think that would be nice too.

**Comment by ncalcott** [comment]
I added in a new 'full-width' image size in the functions.php file and implemented that in the gallery pages and the carousel to allow for the full 3 column display.  I left the built-in large size unchanged to allow for the slideshows to remain at their current size.  This change won't be implemented site-wide until I re-upload the images at the updated size, but it is functioning correctly when I've done that...

**Comment by halfempty** [comment]
It sounds like this one is complete, so I'll close this ticket.
