### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by halfempty** [everythingtype/calcott#49]
I've begun on this. But not finished.

**Comment by halfempty** [comment]
@gehalber @KyleETC @ncalcott Hey all, made some progress on the site navigation at responsive sizes. I think it's in and working. Take a look?

Responsive conversion of page layouts remains.

**Comment by ncalcott** [comment]
Yep, looks great.  Not working on my iphone at the moment, though it does on browser resize.

**Comment by ncalcott** [comment]
Hey guys - just checking in.  Any timeline for further work on the project?  I've got a bunch of galleries to roll out and I'm sort of waiting for the site update to be completed...

**Comment by halfempty** [comment]
@ncalcott @gehalber Update: Added some responsive breakpoints to the "Gallery" template. Example: http://www.nicholascalcott.com/portfolios/metropolitan-museum-for-t-magazine/

**Comment by halfempty** [comment]
@ncalcott I've put in a couple of breakpoints on the "Index" page

Nick-- are there any pages/sections where we should massage the breakpoints further?

**Comment by ncalcott** [comment]
What should I be looking for on with the 'breakpoints', btw?  I'm not really seeing a difference...

**Comment by halfempty** [comment]
@ncalcott Breakpoints are where the layout changes at different pixel sizes. For instance, going from three columns, to two, to one. I guess what I'm saying is, please let me know if you see any situations where you think something is inappropriate (say, too large or too small) at a given window size. 

I'll close this issue, and when you see something, open a new ticket for it.
