### ISSUE TITLE
Bugs On Galleries

### ISSUE THREAD

**Issue by ncalcott** [everythingtype/calcott#50]
There's a series of bugs that have shown up on some of the gallery pages since the updating process began.  On the index galleries (http://www.nicholascalcott.com/index/), all the thumbnails are showing up small.  And in the main galleries, they occasionally seem to show up with incorrect spacing or overlapping.

**Comment by ncalcott** [comment]
I'd love to fix this issue asap, as it's affecting some of the core function of the site...

**Comment by ncalcott** [comment]
The main gallery issue is the priority for me - the index gallery stuff can wait until the rest is solved.

**Comment by halfempty** [comment]
@ncalcott Both "main" and "index" galleries use the same template. I *think* the only difference between them is that the "index" ones are more likely to have more images on them.

Is this the same as what we observed in issue #47, "Bug on Long Pages"?

**Comment by ncalcott** [comment]
I don't think it's the length 'cause this happens even in index galleries with only a few images (http://www.nicholascalcott.com/index/dog/).

And I can't replicate the main gallery issues - I observed it over the weekend, can't get it to happen again.  I'll keep an eye out for it, though.

**Comment by halfempty** [comment]
@ncalcott I'm in there now looking the culprit. Things might be wonky while I'm making changes, just a heads-up.

**Comment by halfempty** [comment]
@ncalcott Made a change related to "index" galleries (there WAS a difference from the "main"). Can you take a look and let me know if you see any improvement there?

**Comment by ncalcott** [comment]
Yep, all good now!  Thanks!

I guess you can mark this as 'closed.'  I'll reopen if I observe some weird behavior on the main galleries, but I'm thinking it might have just been related to the known bug on long pages - I was showing someone else the site, so I didn't have time to explore what was going on, but just clicked through.

**Comment by halfempty** [comment]
Cool!
