### ISSUE TITLE
Stray enqueue.php?

### ISSUE THREAD

**Issue by halfempty** [everythingtype/calcott#52]
@ncalcott Just checking your updates into version control. I notice there's what looks to be a copy of the  enqueue.php file, chilling out in the theme directory. Eyeballing for changes, it looks like there's a reference to an "instafeedcontrljs" JS file. 

I'm guessing it's from an attempt to quash the instragram bug, but didn't make it into the final. Is it cool if I nix this stray file?

**Comment by ncalcott** [comment]
Yep, that's right - it was a failed attempt and I thought I had gone through and deleted the changes.  Go ahead and remove that one.  Thanks!

**Comment by halfempty** [comment]
Done, cheers
